server:
  port: 9000

spring:
  application:
    name: campus-gateway
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 3000ms
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user-service
          uri: lb://campus-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: club-service
          uri: lb://campus-club-service
          predicates:
            - Path=/club/**
          filters:
            - StripPrefix=1
        - id: im-service
          uri: lb://campus-im-service
          predicates:
            - Path=/im/**
          filters:
            - StripPrefix=1
        - id: seckill-service
          uri: lb://campus-seckill-service
          predicates:
            - Path=/seckill/**
          filters:
            - StripPrefix=1
        - id: file-service
          uri: lb://campus-file-service
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1

campus:
  jwt:
    secret: ${CAMPUS_JWT_SECRET}
    access-expire: 7200000    # 2小时（毫秒）
    refresh-expire: 604800000 # 7天（毫秒）
